Public Class LiquidacionReporte
    Public Property Año As String
    Public Property Mes As String
    Public Property Nombreusr As String
    Public Property Rut As String
    Public Property TLiquido As Double
    Public Property Dias As String
    Public Property Base As Double
    Public Property TGratificacion As Double
    Public Property TImponible As Double
    Public Property TColacion As Double
    Public Property TMovilizacion As Double
    Public Property TCargas As Double
    Public Property THaberes As Double
    Public Property TAFP As Double
    Public Property TSalud As Double
    Public Property Anticipados As Double
    Public Property Descuentos As Double
    Public Property TDescuentos As Double
    Public Property Ahorros As Double
    Public Property Seguros As Double
    Public Property Creditos As Double
    Public Property Pactado As Double
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property NombreCiudad As String
    Public Property NombreComuna As String
    Public Property UF As Double
    Public Property NAFP As String
    Public Property NSAlud As String
    Public Property PorcentajeAFP As Double
    Public Property AFC As Double
    Public Property TAguinaldos As Double
    Public Property TBonos2 As Double
    Public Property Cargas As Double
    Public Property PorcentajeSalud As Double
    Public Property TBonos As Double
    Public Property TVariables As Double
    Public Property Vigencia As Date
    Public Property Letras As String
    Public Property ImpuestoUnico As Double
    Public Property RutEmpresa As String
    Public Property Prueba_Campo As String
End Class
